{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Bingo Player API",
    "description": "Documentation of the Bingo Player API"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/": {
      "get": {
        "description": "",
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal server error.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "501": {
            "description": "Not implemented.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "ok": false,
                "code": "NOT_IMPLEMENTED",
                "message": "Not implemented",
                "help": "https://example.com/docs"
              }
            }
          }
        }
      }
    },
    "/ping": {
      "get": {
        "tags": [
          "General"
        ],
        "description": "  Ping the server to ensure the API is up and running.  It should respond with a 200 response and the text \"pong\".  ",
        "responses": {
          "200": {
            "description": "Server is up and running.",
            "schema": {
              "type": "string",
              "example": "pong",
              "xml": {
                "name": "main"
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "501": {
            "description": "Not implemented.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "ok": false,
                "code": "NOT_IMPLEMENTED",
                "message": "Not implemented",
                "help": "https://example.com/docs"
              }
            }
          }
        }
      }
    },
    "/api/v1/spaces/get/all": {
      "get": {
        "tags": [
          "Spaces"
        ],
        "description": "Get all spaces in the database.",
        "responses": {
          "200": {
            "description": "Spaces found",
            "schema": {
              "type": "object",
              "properties": {
                "ok": {
                  "type": "boolean",
                  "example": true
                },
                "spaces": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/CleanMongoSpace"
                  }
                },
                "help": {
                  "type": "string",
                  "example": "https://example.com/docs"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "404": {
            "description": "No matching spaces found.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "ok": false,
                "code": "NOT_FOUND",
                "message": "No spaces found.",
                "help": "https://example.com/docs"
              }
            }
          }
        }
      }
    },
    "/api/v1/spaces/count/all": {
      "get": {
        "tags": [
          "Spaces"
        ],
        "description": "Get the number of spaces in the database.",
        "responses": {
          "200": {
            "description": "Number of spaces found",
            "schema": {
              "type": "object",
              "properties": {
                "ok": {
                  "type": "boolean",
                  "example": true
                },
                "count": {
                  "type": "number",
                  "example": 42
                },
                "help": {
                  "type": "string",
                  "example": "https://example.com/docs"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "404": {
            "description": "No spaces found.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "ok": false,
                "code": "NOT_FOUND",
                "message": "No spaces found.",
                "help": "https://example.com/docs"
              }
            }
          }
        }
      }
    },
    "/api/v1/spaces/get/all/list/{prop}": {
      "get": {
        "tags": [
          "Spaces"
        ],
        "description": "Get all values for a given space query prop.",
        "parameters": [
          {
            "name": "prop",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "The space query prop to list."
          }
        ],
        "responses": {
          "200": {
            "description": "List of values found",
            "schema": {
              "type": "object",
              "properties": {
                "ok": {
                  "type": "boolean",
                  "example": true
                },
                "values": {
                  "type": "array",
                  "example": [
                    "value1",
                    "value2"
                  ],
                  "items": {
                    "type": "string"
                  }
                },
                "help": {
                  "type": "string",
                  "example": "https://example.com/docs"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400": {
            "description": "Invalid input",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "ok": false,
                "code": "BAD_INPUT",
                "message": "Invalid space query prop",
                "help": "https://example.com/docs"
              }
            }
          },
          "404": {
            "description": "No matching spaces found.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "ok": false,
                "code": "NOT_FOUND",
                "message": "No matching spaces found.",
                "help": "http://example.com/docs"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Space": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "examples": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "aliases": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "id",
        "name"
      ]
    },
    "CleanSpace": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "examples": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "aliases": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "id",
        "name",
        "description",
        "examples",
        "aliases",
        "tags"
      ]
    },
    "MongoSpace": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "examples": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "aliases": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "_id",
        "name"
      ]
    },
    "CleanMongoSpace": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "examples": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "aliases": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "_id",
        "name",
        "description",
        "examples",
        "aliases",
        "tags"
      ]
    },
    "ErrorCode": {
      "type": "string",
      "enum": [
        "UNKNOWN",
        "BAD_INPUT",
        "INTERNAL",
        "NOT_FOUND",
        "NOT_IMPLEMENTED"
      ]
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "ok": {
          "type": "boolean",
          "enum": [
            false
          ]
        },
        "code": {
          "$ref": "#/definitions/ErrorCode"
        },
        "message": {
          "type": "string"
        },
        "help": {
          "type": "string",
          "required": false,
          "description": "URL to the documentation"
        }
      }
    }
  }
}